'use client';

import { FormEvent, useMemo, useState } from 'react';

const problems = ['Denied treatment days', 'Authorization gaps', 'Medical-necessity weaknesses', 'Underpaid claims', 'A/R that keeps aging'];

const auditAreas = [
  ['01', 'Authorization', 'Dates, level of care, concurrent reviews, requests, approvals, reductions, and denials.'],
  ['02', 'Medical necessity', 'Whether the record actually supports the documented clinical need and level of care.'],
  ['03', 'Documentation', 'Missing, inconsistent, late, or disconnected documentation that can weaken a claim.'],
  ['04', 'Coding + claims', 'Whether coding, units, dates, place of service, and claim data match the underlying record.'],
  ['05', 'Payments', 'Underpayments, contractual variances, reductions, recoupments, and unexplained balances.'],
  ['06', 'Denials + recovery', 'Patterns in denials and appeal opportunities that deserve a second look.'],
];

const workflow = ['Clinical presentation', 'Diagnosis & severity', 'Medical necessity', 'Level of care', 'Treatment plan', 'Interventions', 'Response to treatment', 'Continued-stay rationale', 'Authorization', 'Coding', 'Claim', 'Payment'];
const payerGroups = ['Aetna', 'UHC / Optum', 'Cigna', 'Anthem / Elevance', 'BCBS plans', 'Carelon', 'Magellan', 'Medicaid MCOs'];

function money(value: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
}

export default function Home() {
  const [beds, setBeds] = useState(40);
  const [occupancy, setOccupancy] = useState(85);
  const [dailyRate, setDailyRate] = useState(650);
  const [denialRate, setDenialRate] = useState(8);
  const [submitted, setSubmitted] = useState(false);

  const revenueAtRisk = useMemo(() => beds * (occupancy / 100) * 365 * dailyRate * (denialRate / 100), [beds, occupancy, dailyRate, denialRate]);

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
  }

  return (
    <main className="min-h-screen overflow-hidden bg-[#05070b] text-slate-100">
      <nav className="sticky top-0 z-30 border-b border-white/10 bg-[#05070b]/85 backdrop-blur-xl">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8">
          <a href="#top" className="text-sm font-semibold tracking-[.14em] text-white">REVENUE INTELLIGENCE</a>
          <div className="hidden items-center gap-8 text-sm text-slate-400 md:flex">
            <a href="#problem" className="transition hover:text-white">2026 problem</a><a href="#audit" className="transition hover:text-white">Audit</a><a href="#model" className="transition hover:text-white">Documentation</a><a href="#calculator" className="transition hover:text-white">Estimate</a>
          </div>
          <a href="#contact" className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-teal-200">Request review</a>
        </div>
      </nav>

      <section id="top" className="noise relative border-b border-white/10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_15%,rgba(45,212,191,.13),transparent_35%)]" />
        <div className="relative mx-auto grid max-w-7xl gap-16 px-6 py-24 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:py-32">
          <div>
            <div className="mb-7 inline-flex items-center rounded-full border border-teal-300/20 bg-teal-300/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.22em] text-teal-200">2026 Revenue Intelligence · DTX + RTC</div>
            <h1 className="max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.045em] text-white sm:text-6xl lg:text-8xl">You delivered the care.<span className="mt-3 block text-teal-300">Now find the money you didn&apos;t collect.</span></h1>
            <p className="mt-8 max-w-2xl text-lg leading-8 text-slate-400 sm:text-xl">We audit the chain between clinical documentation, medical necessity, authorization, coding, claims, and payment to find where legitimate revenue is being lost.</p>
            <div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="rounded-full bg-teal-300 px-7 py-4 text-center text-sm font-bold text-slate-950 shadow-[0_0_40px_rgba(45,212,191,.18)] transition hover:bg-teal-200">Request a free revenue screening</a><a href="#calculator" className="rounded-full border border-white/15 bg-white/[.03] px-7 py-4 text-center text-sm font-semibold text-white transition hover:bg-white/[.07]">Estimate revenue at risk</a></div>
            <div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-xs uppercase tracking-[.18em] text-slate-500"><span>Residential</span><span>Detox</span><span>PHP</span><span>IOP</span><span>Commercial</span><span>Medicaid</span></div>
          </div>
          <div className="glow glass self-end rounded-[28px] border border-white/10 p-7 lg:p-8">
            <div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Revenue leakage map</p><p className="mt-1 text-sm text-slate-300">Where payment can break</p></div><span className="rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-teal-200">Audit</span></div>
            <div className="mt-6 space-y-2">{problems.map((problem, index) => <div key={problem} className="group flex items-center gap-4 rounded-2xl border border-white/[.07] bg-white/[.025] px-4 py-4 transition hover:border-teal-300/30 hover:bg-teal-300/[.04]"><span className="font-mono text-xs text-slate-600">0{index + 1}</span><span className="text-sm font-medium text-slate-200">{problem}</span><span className="ml-auto text-slate-600 transition group-hover:text-teal-300">→</span></div>)}</div>
            <div className="mt-6 rounded-2xl bg-white/[.035] p-4"><p className="text-xs leading-5 text-slate-500">The goal is not to manufacture documentation or chase artificial reimbursement. It is to identify where the record, authorization, claim, or payment process failed to capture care that was actually provided.</p></div>
          </div>
        </div>
      </section>

      <section id="problem" className="border-b border-white/10 bg-[#080b10]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-28">
        <div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">The 2026 problem</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">Billing is only the last step.</h2><p className="mt-6 max-w-md text-sm leading-6 text-slate-500">In 2026, prior authorization is under increased scrutiny. For certain impacted payers, CMS requires specific denial reasons and sets decision-time requirements. That creates more useful data for providers — if someone actually audits it.</p></div>
          <div><p className="text-xl leading-9 text-slate-300">A clean claim cannot rescue a broken revenue chain. In behavioral health, reimbursement can be affected long before the claim reaches the payer.</p><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{[['01','Documentation','Does the record clearly establish the patient’s documented needs and the care actually delivered?'],['02','Authorization','Do dates, level of care, concurrent reviews, and supporting records line up?'],['03','Coding','Does the code set accurately reflect the documented service and setting?'],['04','Claims','Are claims clean, timely, and consistent with the underlying record?'],['05','Payment','Did the payer actually reimburse what the contract and claim support?'],['06','Recovery','Are denials, reductions, and underpayments being systematically worked?']].map(([num,title,copy]) => <div key={num} className="bg-[#080b10] p-6"><span className="font-mono text-xs text-teal-300">{num}</span><h3 className="mt-4 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-2">{payerGroups.map((payer) => <span key={payer} className="rounded-full border border-white/10 bg-white/[.025] px-3 py-1.5 text-xs text-slate-500">{payer}</span>)}</div></div></div>
        <div className="mt-14 rounded-3xl border border-teal-300/15 bg-teal-300/[.035] p-7 lg:p-8"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-300">Why this matters now</p><h3 className="mt-3 text-2xl font-semibold text-white">Denial data is becoming more actionable.</h3><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">CMS says impacted payers must provide a specific reason for certain prior-authorization denials beginning in 2026. Recent HHS-OIG work also shows that behavioral-health authorization denials can fail administrative and procedural requirements. We turn those signals into an audit trail.</p></div><a href="#sources" className="rounded-full border border-teal-300/25 px-5 py-3 text-center text-sm font-semibold text-teal-200">See sources</a></div></div>
      </div></section>

      <section id="audit" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">What we audit</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">We trace the denial back to where it started.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Not just a denial report. A forensic review of the chain connecting the clinical record, authorization, claim, and payment.</p></div>
        <div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{auditAreas.map(([num,title,copy]) => <div key={num} className="group rounded-[26px] border border-white/10 bg-white/[.025] p-7 transition duration-300 hover:-translate-y-1 hover:border-teal-300/30 hover:bg-white/[.04]"><span className="font-mono text-xs text-teal-300">{num}</span><h3 className="mt-12 text-2xl font-semibold text-white">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div>
        <div className="mt-10 grid gap-5 lg:grid-cols-3">{[['Denied RTC day','We compare the billed day against authorization dates, level-of-care support, concurrent-review history, and the underlying record.'],['Underpaid claim','We compare what was billed and contracted against what was actually paid, then identify whether a variance deserves investigation.'],['Repeat denial pattern','We group denials by payer, facility, level of care, reason, clinician, date range, and workflow step to find systemic causes.']].map(([title,copy],index) => <div key={title} className="rounded-2xl border border-white/10 bg-[#080b10] p-6"><span className="text-xs font-mono text-slate-600">CASE 0{index+1}</span><h3 className="mt-4 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div>
      </div></section>

      <section id="calculator" className="border-b border-white/10 bg-[#080b10]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">Illustrative revenue screen</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">How much revenue could be at risk?</h2><p className="mt-5 text-lg leading-8 text-slate-400">Adjust the assumptions to see an illustrative annual gross revenue-at-risk figure. This is a screening tool, not a prediction of recoverable revenue.</p><a href="#contact" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-slate-950 transition hover:bg-teal-200">Find your actual number →</a></div>
          <div className="rounded-[28px] border border-white/10 bg-[#05070b] p-7 lg:p-8"><div className="grid gap-7 sm:grid-cols-2">{[
            ['RTC / DTX beds', beds, setBeds, 1, 200, 1], ['Average occupancy %', occupancy, setOccupancy, 1, 100, 1], ['Average reimbursable day', dailyRate, setDailyRate, 100, 3000, 50], ['Denial / non-collection %', denialRate, setDenialRate, 0.5, 30, 0.5],
          ].map(([label,value,setter,min,max,step]) => <label key={label as string} className="block"><div className="flex items-center justify-between text-sm font-semibold text-white"><span>{label as string}</span><span className="text-teal-300">{label === 'Average reimbursable day' ? money(value as number) : `${value}${String(label).includes('%') ? '%' : ''}`}</span></div><input aria-label={label as string} type="range" min={min as number} max={max as number} step={step as number} value={value as number} onChange={(e) => (setter as (v:number)=>void)(Number(e.target.value))} className="mt-5 w-full accent-teal-300" /></label>)}</div><div className="mt-8 rounded-2xl border border-teal-300/20 bg-teal-300/[.06] p-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-300">Illustrative annual revenue at risk</p><p className="mt-3 text-5xl font-semibold tracking-tight text-white">{money(revenueAtRisk)}</p><p className="mt-3 text-xs leading-5 text-slate-500">Occupied days × average reimbursable day × stated non-collection rate. Actual recovery depends on claim facts, contracts, authorization, documentation, payer rules, and audit findings.</p></div></div>
        </div></div></section>

      <section id="model" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-28"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">Documentation intelligence</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">Stop treating documentation and billing as separate systems.</h2><p className="mt-6 text-base leading-7 text-slate-400">We are developing a behavioral-health documentation and coding workflow around clinical truth, medical necessity, level-of-care rationale, payer requirements, and billing consistency.</p><p className="mt-5 text-sm leading-6 text-slate-500">The system is not designed to manufacture or pad notes. It is designed to help teams identify missing, inconsistent, or unsupported information before it becomes a denial or recoupment risk.</p></div><div><div className="mb-5 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Revenue chain</span><span className="text-xs text-teal-300">01 — 12</span></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{workflow.map((step,index)=><div key={step} className="flex min-h-[92px] flex-col justify-between rounded-2xl border border-white/10 bg-[#05070b] p-4"><span className="font-mono text-[10px] text-slate-600">{String(index+1).padStart(2,'0')}</span><span className="text-sm font-medium text-slate-200">{step}</span></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[.02] p-5 text-sm leading-6 text-slate-500">The objective is simple: the clinical record should accurately reflect the care actually provided, and the coding and claim should remain consistent with that record.</div></div></div></div></section>

      <section id="contact" className="relative border-b border-white/10 bg-[#080b10]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_100%,rgba(45,212,191,.1),transparent_45%)]" /><div className="relative mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">Start here</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">Let&apos;s find out where your revenue is leaking.</h2><p className="mt-5 text-lg leading-8 text-slate-500">Tell us about the facility. We&apos;ll determine whether a free screening, comprehensive audit, or recovery engagement makes the most sense.</p><div className="mt-8 space-y-3 text-sm text-slate-500"><p>✓ No patient-identifying information required for the initial screening.</p><p>✓ Start with a limited sample before committing to a full audit.</p><p>✓ Recovery-based structures may be available for qualified engagements.</p></div></div>
          <form onSubmit={handleSubmit} className="glass rounded-[28px] border border-white/10 p-7 lg:p-8">{submitted ? <div className="py-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-teal-300 text-xl font-bold text-slate-950">✓</div><h3 className="mt-5 text-2xl font-semibold text-white">Request received.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-500">The public form is ready for connection to the company inbox or CRM. No PHI was requested or transmitted.</p><button type="button" onClick={()=>setSubmitted(false)} className="mt-6 text-sm font-semibold text-teal-300">Submit another request</button></div> : <div className="grid gap-4 sm:grid-cols-2">{['Facility name','Contact name','Work email','Phone','DTX / RTC beds','Primary payers'].map(label=><input key={label} required={label!=='Phone'} placeholder={label} className="rounded-xl border border-white/10 bg-white/[.035] px-4 py-3.5 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-teal-300/50 focus:bg-white/[.06]" />)}<textarea placeholder="What is your biggest revenue or billing concern?" rows={4} className="sm:col-span-2 rounded-xl border border-white/10 bg-white/[.035] px-4 py-3.5 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-teal-300/50 focus:bg-white/[.06]" /><button type="submit" className="sm:col-span-2 rounded-xl bg-teal-300 px-6 py-4 text-sm font-bold text-slate-950 transition hover:bg-teal-200">Request confidential review →</button></div>}<p className="mt-4 text-center text-[11px] leading-5 text-slate-600">Do not submit patient-identifying information or PHI through this public form.</p></form>
        </div></div></section>

      <section id="sources" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-teal-300">Research basis</p><div className="mt-6 grid gap-4 md:grid-cols-3"><a href="https://www.cms.gov/newsroom/fact-sheets/cms-interoperability-prior-authorization-final-rule-cms-0057-f" target="_blank" rel="noreferrer" className="rounded-2xl border border-white/10 bg-white/[.02] p-5 transition hover:border-teal-300/30"><p className="font-semibold text-white">CMS prior authorization rule</p><p className="mt-2 text-sm leading-6 text-slate-500">Specific denial reasons and decision-time requirements for impacted payers beginning in 2026.</p></a><a href="https://www.oig.hhs.gov/reports/all/2026/community-behavioral-health-did-not-comply-with-requirements-when-denying-prior-authorization-requests/" target="_blank" rel="noreferrer" className="rounded-2xl border border-white/10 bg-white/[.02] p-5 transition hover:border-teal-300/30"><p className="font-semibold text-white">HHS-OIG behavioral health audit</p><p className="mt-2 text-sm leading-6 text-slate-500">A 2026 audit found procedural problems in sampled behavioral-health prior-authorization denials.</p></a><a href="https://www.cms.gov/data-research/computer-data-systems/esmd/reason-statements-and-document-emdr-codes" target="_blank" rel="noreferrer" className="rounded-2xl border border-white/10 bg-white/[.02] p-5 transition hover:border-teal-300/30"><p className="font-semibold text-white">CMS denial reason framework</p><p className="mt-2 text-sm leading-6 text-slate-500">CMS describes detailed denial/non-affirmation reasons used in medical review.</p></a></div><p className="mt-6 text-xs leading-5 text-slate-600">Sources are provided for context and do not constitute legal, coding, clinical, or reimbursement advice. Payer requirements and contractual terms vary.</p></div></section>

      <footer className="px-6 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>Revenue Intelligence · Behavioral Health</span><span>Clinical documentation should accurately reflect services actually provided.</span></div></footer>
    </main>
  );
}
