'use client';

import { FormEvent, useMemo, useState } from 'react';

const leakage = ['Denied treatment days', 'Authorization gaps', 'Medical-necessity weaknesses', 'Underpaid claims', 'A/R that keeps aging'];
const payers = ['Aetna', 'UHC / Optum', 'Cigna', 'Anthem / Elevance', 'BCBS plans', 'Carelon', 'Magellan', 'Medicaid MCOs'];
const chain = ['Clinical presentation', 'Diagnosis & severity', 'Medical necessity', 'Level of care', 'Treatment plan', 'Interventions', 'Response to treatment', 'Continued-stay rationale', 'Authorization', 'Coding', 'Claim', 'Payment'];
const audits = [
  ['01', 'Authorization', 'Dates, level of care, concurrent reviews, approvals, reductions, and denials.'],
  ['02', 'Medical necessity', 'Whether the record supports the documented clinical need and level of care.'],
  ['03', 'Documentation', 'Missing, inconsistent, late, or disconnected documentation that can weaken a claim.'],
  ['04', 'Coding + claims', 'Whether coding, units, dates, place of service, and claim data match the record.'],
  ['05', 'Payments', 'Underpayments, contractual variances, reductions, recoupments, and unexplained balances.'],
  ['06', 'Denials + recovery', 'Patterns in denials and appeal opportunities that deserve a second look.'],
];

const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

export default function Home() {
  const [beds, setBeds] = useState(40), [occupancy, setOccupancy] = useState(85), [rate, setRate] = useState(650), [denial, setDenial] = useState(8);
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
  const risk = useMemo(() => beds * occupancy / 100 * 365 * rate * denial / 100, [beds, occupancy, rate, denial]);

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setStatus('sending');
    const data = Object.fromEntries(new FormData(e.currentTarget).entries());
    const response = await fetch('/api/lead', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    setStatus(response.ok ? 'success' : 'error');
  }

  return <main className="min-h-screen bg-[#05070b] text-slate-100">
    <nav className="sticky top-0 z-30 border-b border-white/10 bg-[#05070b]/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8"><a href="#top" className="text-sm font-semibold tracking-[.14em] text-white">REVENUE INTELLIGENCE</a><div className="hidden gap-8 text-sm text-slate-400 md:flex"><a href="#problem">2026 problem</a><a href="#audit">Audit</a><a href="#model">Documentation</a><a href="#calculator">Estimate</a></div><a href="#contact" className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-950">Request review</a></div></nav>

    <section id="top" className="noise relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_15%,rgba(45,212,191,.13),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-16 px-6 py-24 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:py-32"><div><span className="inline-flex rounded-full border border-teal-300/20 bg-teal-300/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.22em] text-teal-200">2026 Revenue Intelligence · DTX + RTC</span><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.045em] text-white sm:text-6xl lg:text-8xl">You delivered the care.<span className="mt-3 block text-teal-300">Now find the money you didn&apos;t collect.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-400 sm:text-xl">We audit the chain between clinical documentation, medical necessity, authorization, coding, claims, and payment to find where legitimate revenue is being lost.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="rounded-full bg-teal-300 px-7 py-4 text-center text-sm font-bold text-slate-950">Request a free revenue screening</a><a href="#calculator" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-semibold text-white">Estimate revenue at risk</a></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-xs uppercase tracking-[.18em] text-slate-500"><span>Residential</span><span>Detox</span><span>PHP</span><span>IOP</span><span>Commercial</span><span>Medicaid</span></div></div><div className="glass self-end rounded-[28px] border border-white/10 p-7"><div className="flex justify-between border-b border-white/10 pb-5"><div><p className="text-xs uppercase tracking-[.2em] text-slate-500">Revenue leakage map</p><p className="mt-1 text-sm text-slate-300">Where payment can break</p></div><span className="rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1 text-[10px] font-bold uppercase text-teal-200">Audit</span></div><div className="mt-6 space-y-2">{leakage.map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-white/[.07] bg-white/[.025] px-4 py-4"><span className="font-mono text-xs text-slate-600">0{i+1}</span><span className="text-sm font-medium text-slate-200">{x}</span><span className="ml-auto text-slate-600">→</span></div>)}</div><p className="mt-6 rounded-2xl bg-white/[.035] p-4 text-xs leading-5 text-slate-500">The goal is not to manufacture documentation or chase artificial reimbursement. It is to identify where the record, authorization, claim, or payment process failed to capture care actually provided.</p></div></div></section>

    <section id="problem" className="border-b border-white/10 bg-[#080b10]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">The 2026 problem</p><h2 className="section-title">Billing is only the last step.</h2><p className="mt-6 max-w-md text-sm leading-6 text-slate-500">Prior authorization is under increased scrutiny. For certain impacted payers, CMS requires specific denial reasons and decision-time requirements beginning in 2026.</p></div><div><p className="text-xl leading-9 text-slate-300">A clean claim cannot rescue a broken revenue chain. In behavioral health, reimbursement can be affected long before the claim reaches the payer.</p><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{audits.map(([n,t,c])=><div key={n} className="bg-[#080b10] p-6"><span className="font-mono text-xs text-teal-300">{n}</span><h3 className="mt-4 font-semibold text-white">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{c}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-2">{payers.map(p=><span key={p} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-500">{p}</span>)}</div></div></div><div className="mt-14 rounded-3xl border border-teal-300/15 bg-teal-300/[.035] p-7"><p className="eyebrow">Why this matters now</p><h3 className="mt-3 text-2xl font-semibold text-white">Denial data is becoming more actionable.</h3><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-400">CMS says impacted payers must provide a specific reason for certain prior-authorization denials beginning in 2026. Recent HHS-OIG work also found procedural problems in sampled behavioral-health authorization denials. We turn those signals into an audit trail.</p></div></div></section>

    <section id="audit" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><p className="eyebrow">What we audit</p><h2 className="section-title max-w-4xl">We trace the denial back to where it started.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-400">Not just a denial report. A forensic review of the chain connecting the clinical record, authorization, claim, and payment.</p><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[['Denied RTC day','Authorization dates, concurrent review history, level-of-care support, and the billed day.'],['Underpaid claim','Billed amount, contractual expectations, actual payment, and variance.'],['Repeat denial pattern','Payer, level of care, reason, date range, and workflow step grouped to expose systemic causes.']].map(([t,c],i)=><div key={t} className="rounded-[26px] border border-white/10 bg-white/[.025] p-7"><span className="font-mono text-xs text-teal-300">CASE 0{i+1}</span><h3 className="mt-12 text-2xl font-semibold text-white">{t}</h3><p className="mt-4 text-sm leading-6 text-slate-500">{c}</p></div>)}</div></div></section>

    <section id="calculator" className="border-b border-white/10 bg-[#080b10]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Illustrative revenue screen</p><h2 className="section-title">How much revenue could be at risk?</h2><p className="mt-5 text-lg leading-8 text-slate-400">Adjust the assumptions. This estimates gross revenue exposed to a stated non-collection rate; it is not a prediction of recoverable dollars.</p></div><div className="rounded-[28px] border border-white/10 bg-[#05070b] p-7"><div className="grid gap-7 sm:grid-cols-2">{[['RTC / DTX beds',beds,setBeds,1,200,1],['Average occupancy %',occupancy,setOccupancy,1,100,1],['Average reimbursable day',rate,setRate,100,3000,50],['Denial / non-collection %',denial,setDenial,.5,30,.5]].map(([label,value,setter,min,max,step])=><label key={label as string}><div className="flex justify-between text-sm font-semibold text-white"><span>{label as string}</span><span className="text-teal-300">{label==='Average reimbursable day'?money(value as number):`${value}${String(label).includes('%')?'%':''}`}</span></div><input aria-label={label as string} type="range" min={min as number} max={max as number} step={step as number} value={value as number} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))} className="mt-5 w-full accent-teal-300"/></label>)}</div><div className="mt-8 rounded-2xl border border-teal-300/20 bg-teal-300/[.06] p-6"><p className="eyebrow">Illustrative annual revenue at risk</p><p className="mt-3 text-5xl font-semibold text-white">{money(risk)}</p><p className="mt-3 text-xs leading-5 text-slate-500">Occupied days × average reimbursable day × stated non-collection rate. Actual recovery depends on claim facts, contracts, authorization, documentation, payer rules, and audit findings.</p></div></div></div></div></section>

    <section id="model" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Documentation intelligence</p><h2 className="section-title">Stop treating documentation and billing as separate systems.</h2><p className="mt-6 text-base leading-7 text-slate-400">We are developing a behavioral-health documentation and coding workflow around clinical truth, medical necessity, level-of-care rationale, payer requirements, and billing consistency.</p><p className="mt-5 text-sm leading-6 text-slate-500">The system is not designed to manufacture or pad notes. It helps teams identify missing, inconsistent, or unsupported information before it becomes a denial or recoupment risk.</p></div><div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{chain.map((x,i)=><div key={x} className="flex min-h-[92px] flex-col justify-between rounded-2xl border border-white/10 bg-[#05070b] p-4"><span className="font-mono text-[10px] text-slate-600">{String(i+1).padStart(2,'0')}</span><span className="text-sm font-medium text-slate-200">{x}</span></div>)}</div></div></div></div></section>

    <section id="contact" className="border-b border-white/10 bg-[#080b10]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Start here</p><h2 className="section-title">Let&apos;s find out where your revenue is leaking.</h2><p className="mt-5 text-lg leading-8 text-slate-500">Start with a limited sample. We will determine whether a free screening, comprehensive audit, or recovery engagement makes the most sense.</p><div className="mt-8 space-y-3 text-sm text-slate-500"><p>✓ No patient-identifying information required.</p><p>✓ Start small before committing to a full audit.</p><p>✓ Recovery-based structures may be available for qualified engagements.</p></div></div><form onSubmit={submit} className="glass rounded-[28px] border border-white/10 p-7"><div className="grid gap-4 sm:grid-cols-2"><input name="facilityName" required placeholder="Facility name" className="field"/><input name="contactName" required placeholder="Contact name" className="field"/><input name="email" type="email" required placeholder="Work email" className="field"/><input name="phone" placeholder="Phone" className="field"/><input name="beds" required placeholder="DTX / RTC beds" className="field"/><input name="payers" required placeholder="Primary payers" className="field"/><textarea name="concern" placeholder="What is your biggest revenue or billing concern?" rows={4} className="field sm:col-span-2"/><button disabled={status==='sending'} className="sm:col-span-2 rounded-xl bg-teal-300 px-6 py-4 text-sm font-bold text-slate-950 disabled:opacity-60">{status==='sending'?'Sending…':'Request confidential review →'}</button></div>{status==='success'&&<p className="mt-4 text-center text-sm text-teal-300">Request sent. We will follow up using the contact information provided.</p>}{status==='error'&&<p className="mt-4 text-center text-sm text-red-300">The request could not be delivered yet. Please try again or use the company contact method once configured.</p>}<p className="mt-4 text-center text-[11px] leading-5 text-slate-600">Do not submit patient-identifying information or PHI through this public form.</p></form></div></div></section>

    <section id="sources" className="border-b border-white/10"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><p className="eyebrow">Research basis</p><div className="mt-6 grid gap-4 md:grid-cols-3"><a target="_blank" rel="noreferrer" href="https://www.cms.gov/newsroom/fact-sheets/cms-interoperability-prior-authorization-final-rule-cms-0057-f" className="source">CMS prior authorization rule<span>Specific denial reasons and decision-time requirements for impacted payers beginning in 2026.</span></a><a target="_blank" rel="noreferrer" href="https://www.oig.hhs.gov/reports/all/2026/community-behavioral-health-did-not-comply-with-requirements-when-denying-prior-authorization-requests/" className="source">HHS-OIG behavioral health audit<span>2026 findings on procedural problems in behavioral-health prior-authorization denials.</span></a><a target="_blank" rel="noreferrer" href="https://www.cms.gov/data-research/computer-data-systems/esmd/reason-statements-and-document-emdr-codes" className="source">CMS denial reason framework<span>CMS documentation of detailed denial/non-affirmation reasons used in medical review.</span></a></div><p className="mt-6 text-xs leading-5 text-slate-600">Sources are provided for context and do not constitute legal, coding, clinical, or reimbursement advice. Payer requirements and contracts vary.</p></div></section>
    <footer className="px-6 py-8"><div className="mx-auto flex max-w-7xl justify-between text-xs text-slate-600"><span>Revenue Intelligence · Behavioral Health</span><span>Clinical documentation should accurately reflect services actually provided.</span></div></footer>
  </main>;
}
